import type { CardTemplateDefinition } from "../cardTypes";
import { CARD_FONT_FAMILY, COMMON_CARD_FIELDS } from "./fields";

export const qrCodeTemplate: CardTemplateDefinition = {
  id: "qr-code",
  name: "QR Code",
  description: "A contact card with a QR code linking to your chosen URL.",
  background: "#101c2b",
  fields: [
    ...COMMON_CARD_FIELDS,
    {
      key: "qrUrl",
      label: "QR code destination",
      inputType: "url",
      placeholder: "https://example.com",
      initialValue: "https://example.com",
      required: true,
      autocomplete: "url",
    },
  ],
  layout: [
    {
      id: "accent",
      kind: "shape",
      shape: "rectangle",
      x: 0,
      y: 0,
      width: 3,
      height: 50,
      fill: "#d7b779",
    },
    {
      id: "fullName",
      kind: "text",
      field: "fullName",
      x: 8,
      y: 8,
      width: 51,
      height: 8,
      fontSize: 15,
      fontFamily: CARD_FONT_FAMILY,
      fontWeight: 700,
      color: "#ffffff",
      align: "left",
    },
    {
      id: "role",
      kind: "text",
      field: "role",
      x: 8,
      y: 17,
      width: 51,
      height: 5,
      fontSize: 8,
      fontFamily: CARD_FONT_FAMILY,
      fontWeight: 500,
      color: "#d7b779",
      align: "left",
    },
    {
      id: "email",
      kind: "text",
      field: "email",
      x: 8,
      y: 28,
      width: 51,
      height: 4,
      fontSize: 6.5,
      fontFamily: CARD_FONT_FAMILY,
      fontWeight: 400,
      color: "#e4e8ed",
      align: "left",
    },
    {
      id: "phone",
      kind: "text",
      field: "phone",
      x: 8,
      y: 34,
      width: 51,
      height: 4,
      fontSize: 6.5,
      fontFamily: CARD_FONT_FAMILY,
      fontWeight: 400,
      color: "#e4e8ed",
      align: "left",
    },
    {
      id: "website",
      kind: "text",
      field: "website",
      x: 8,
      y: 40,
      width: 51,
      height: 4,
      fontSize: 6.5,
      fontFamily: CARD_FONT_FAMILY,
      fontWeight: 500,
      color: "#d7b779",
      align: "left",
    },
    {
      id: "qr",
      kind: "qr-code",
      field: "qrUrl",
      x: 64,
      y: 12,
      width: 18,
      height: 18,
    },
  ],
};
