import type { CardTemplateDefinition } from "../cardTypes";
import { CARD_FONT_FAMILY, COMMON_CARD_FIELDS } from "./fields";

export const simpleTemplate: CardTemplateDefinition = {
  id: "simple",
  name: "Simple",
  description: "A clean, text-first business card.",
  background: "#fbfaf7",
  fields: COMMON_CARD_FIELDS,
  layout: [
    {
      id: "accent",
      kind: "shape",
      shape: "rectangle",
      x: 0,
      y: 0,
      width: 3,
      height: 50,
      fill: "#245c57",
    },
    {
      id: "fullName",
      kind: "text",
      field: "fullName",
      x: 9,
      y: 8,
      width: 73,
      height: 8,
      fontSize: 17,
      fontFamily: CARD_FONT_FAMILY,
      fontWeight: 700,
      color: "#172522",
      align: "left",
    },
    {
      id: "role",
      kind: "text",
      field: "role",
      x: 9,
      y: 17,
      width: 73,
      height: 5,
      fontSize: 9,
      fontFamily: CARD_FONT_FAMILY,
      fontWeight: 500,
      color: "#245c57",
      align: "left",
    },
    {
      id: "email",
      kind: "text",
      field: "email",
      x: 9,
      y: 29,
      width: 73,
      height: 4,
      fontSize: 7,
      fontFamily: CARD_FONT_FAMILY,
      fontWeight: 400,
      color: "#424a46",
      align: "left",
    },
    {
      id: "phone",
      kind: "text",
      field: "phone",
      x: 9,
      y: 35,
      width: 73,
      height: 4,
      fontSize: 7,
      fontFamily: CARD_FONT_FAMILY,
      fontWeight: 400,
      color: "#424a46",
      align: "left",
    },
    {
      id: "website",
      kind: "text",
      field: "website",
      x: 9,
      y: 41,
      width: 73,
      height: 4,
      fontSize: 7,
      fontFamily: CARD_FONT_FAMILY,
      fontWeight: 500,
      color: "#245c57",
      align: "left",
    },
  ],
};
